### ISSUE TITLE
Add link to docs.witnet.io to the navbar

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/website#26]
Alongside "What is Witnet?" and "How to Participate"

Otherwise it's difficult to find because you have to scroll down or press "How to Participate", but someone looking for documentation may not click there.

**Comment by Tommytrg** [comment]
The website has been redesigned and it should be clear how to go to the docs.

**Comment by tmpolaczyk** [comment]
> The website has been redesigned and it should be clear how to go to the docs.

Ctrl-F "docs"

0 matches

Alright, maybe it's just me

**Comment by Tommytrg** [comment]
Currently, there isn't a "docs" copy but you will be redirected to docs.witnet.io from several buttons:
- Build with witnet x2
- Start mining wit x2
- witnet-rust full archival node
- Ethereum Truffle Box
- What will you build next?
- Full node

We assumed that it's more interesting to go to the documentation with a purpose instead of just seeing the docs. However, we can add a documentation link in the footer for hard-core players who want to go directly to the "docs". I'd to add a "Documentation" element, although it won't appear on your "docs" search :wink:

**Comment by tmpolaczyk** [comment]
That would be nice, thanks. I think I wanted to check the JSON-RPC documentation, and that does not fall under any of the categories (I just want to check it, not build anything with it or run a full node).

**Comment by tmpolaczyk** [comment]
Also, with the current design the first place where I looked at was the top navbar, (/oracle /token /ecosystem /blog), but then I realized that those links do not point to external pages...

**Comment by gabaldon** [comment]
Build with Witnet goes now to the documentation and there is also a link to the docs in the footer.
